apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sakabas-nextjs
  namespace: sakabas-nextjs
  labels:
    app: sakabas-nextjs
  annotations:
    kubernetes.io/ingress.class: gce
    networking.gke.io/managed-certificates: sakabas-nextjs-cert
spec:
  ingressClassName: gce
  tls:
    - hosts:
        - sakabas.com
        - www.sakabas.com
      secretName: sakabas-nextjs-tls
  rules:
    - host: sakabas.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sakabas-nextjs
                port:
                  number: 80
