apiVersion: v1
kind: LimitRange
metadata:
  name: sakabas-nextjs-limits
  namespace: sakabas-nextjs
  labels:
    app: sakabas-nextjs
spec:
  limits:
     - type: Container
       default:
         memory: 512Mi
         cpu: 500m
       defaultRequest:
         memory: 256Mi
         cpu: 250m
       max:
         memory: 1Gi
         cpu: 1000m
       min:
         memory: 64Mi
         cpu: 50m
