apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: sakabas
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "website-lb-ip"
    networking.gke.io/managed-certificates: "web-cert,api-cert"
spec:
  rules:
    - host: "sakabas.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
    - host: "api.sakabas.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
