apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: ramen-mania
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "website-lb-ip"
    networking.gke.io/managed-certificates: "web-cert"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: "ramen-mania.net"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
