apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
  namespace: sakabas
spec:
  limits:
  - default:
      memory: 15Mi
      cpu: "0.05"
    defaultRequest:
      memory: 6Mi
      cpu: "0.01"
    type: Container
