apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: default
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: web
        image: nginx:alpine
        ports:
        - name: http-port
          containerPort: 80
