apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
  namespace: sakabas-nginx
spec:
  limits:
  - default:
      memory: 12Mi
      cpu: "0.002"
    defaultRequest:
      memory: 6Mi
      cpu: "0.0001"
    type: Container
