apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
  namespace: sakabas-nginx
spec:
  limits:
  - default:
      memory: 10Mi
      cpu: "0.002"
    defaultRequest:
      memory: 3Mi
      cpu: "0.0001"
    type: Container
