apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: sakabas-api
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: api
        image: "us-central1-docker.pkg.dev/hello-world-352201/sakabas-api/sakabas-api:latest"
        imagePullPolicy: "Always"
        env:
        - name: "PORT"
          value: "8080"
        - name: "DB_PWD"
          valueFrom:
            secretKeyRef:
              name: db-pwd
              key: db-pwd
        - name: "DB_HOST"
          valueFrom:
            secretKeyRef:
              name: db-host
              key: db-host
        - name: "DB_NAME"
          valueFrom:
            secretKeyRef:
              name: db-name
              key: db-name
        - name: "DB_USER"
          valueFrom:
            secretKeyRef:
              name: db-user
              key: db-user
        - name: "TIDB_PWD"
          valueFrom:
            secretKeyRef:
              name: tidb-pwd
              key: tidb-pwd
        - name: "TIDB_HOST"
          valueFrom:
            secretKeyRef:
              name: tidb-host
              key: tidb-host
        - name: "TIDB_NAME"
          valueFrom:
            secretKeyRef:
              name: tidb-name
              key: tidb-name
        - name: "TIDB_USER"
          valueFrom:
            secretKeyRef:
              name: tidb-user
              key: tidb-user
        - name: "S3_ID"
          valueFrom:
            secretKeyRef:
              name: s3-id
              key: s3-id
        - name: "S3_SECRET"
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: s3-secret
        - name: "S3_REGION"
          valueFrom:
            secretKeyRef:
              name: s3-region
              key: s3-region
        - name: "TIDB_CONFIG_JSON"
          value: "{\"db.password\":\"$(TIDB_PWD)\",\"db.host\":\"$(TIDB_HOST)\",\"db.name\":\"$(TIDB_NAME)\",\"db.user\":\"$(TIDB_USER)\",\"aws.s3.id\":\"$(S3_ID)\",\"aws.s3.secret\":\"$(S3_SECRET)\",\"aws.s3.region\":\"$(S3_REGION)\"}"
        - name: "APP_CONFIG_JSON"
          value: "{\"db.password\":\"$(DB_PWD)\",\"db.host\":\"$(DB_HOST)\",\"db.name\":\"$(DB_NAME)\",\"db.user\":\"$(DB_USER)\",\"aws.s3.id\":\"$(S3_ID)\",\"aws.s3.secret\":\"$(S3_SECRET)\",\"aws.s3.region\":\"$(S3_REGION)\"}"
