apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
  namespace: sakabas-api
spec:
  limits:
  - default:
      memory: 60Mi
    defaultRequest:
      memory: 60Mi
      cpu: "0.05"
    type: Container
