apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
  namespace: sakabas-api
spec:
  limits:
  - default:
      memory: 30Mi
    defaultRequest:
      memory: 30Mi
      cpu: "0.005"
    type: Container
