apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
  namespace: sakabas-api
spec:
  limits:
  - default:
      memory: 15Mi
      cpu: "0.05"
    defaultRequest:
      memory: 10Mi
      cpu: "0.01"
    type: Container
