apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
  namespace: sakabas-api
spec:
  limits:
  - default:
      memory: 100Mi
    defaultRequest:
      memory: 100Mi
      cpu: "0.003"
    type: Container
