apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: sakabas
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api
        image: "us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0"
        env:
        - name: "PORT"
          value: "50000"
